name: build-lib

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
#    - name: Install Qt
#      uses: jurplel/install-qt-action@v2.2.1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -D TRACKERBOY_ENABLE_UI=OFF -D TRACKERBOY_ENABLE_DEMO=OFF -D TRACKERBOY_ENABLE_TESTS=OFF ..
    - name: build
      run: cmake --build build --config Debug
