
name: Build and deploy

on:
  workflow_call:
    inputs:
      buildType:
        required: true
        type: string
      os:
        required: true
        type: string
      arch:
        required: true
        type: string
      platform:
        required: true
        type: string
      qtArch:
        type: string
      qtVersion:
        required: true
        type: string
    outputs:
      artifactName:
        description: "Name of the upload artifact"
        value: ${{ jobs.buildAndDeploy.outputs.artifactName }}

jobs:
  buildAndDeploy:
    name: Build-${{ inputs.os }}-${{ inputs.arch }}-${{ inputs.buildType }}
    runs-on: ${{ inputs.os }}
    outputs:
      artifactName: ${{ steps.getArtifactName.outputs.name }}
    steps:
      - uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest
      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ inputs.arch }}
      
      - name: Install dependencies (linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
          UBUNTU_RELEASE=$(lsb_release -rs)
          UBUNTU_RELEASE=(${UBUNTU_RELEASE//./ })
          if [ ${UBUNTU_RELEASE[0]} -ge 22  ] && [ ${UBUNTU_RELEASE[1]} -ge 04 ]; then
            sudo apt-get install -y libfuse2
          else
            sudo apt-get install -y fuse libfuse2
          fi
          mkdir tools
          cd tools
          wget 'https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage' -nv -O linuxdeploy
          wget 'https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage' -nv -O linuxdeploy-plugin-qt
          chmod a+x linuxdeploy*

      - name: CPM Cache
        id: cache-cpm
        uses: actions/cache@v3
        with:
          path: ~/cpm-cache
          key: ${{ inputs.os }}-${{ inputs.arch }}-cpm-${{ hashFiles('**/') }}
          restore-keys: |
            ${{ inputs.os }}-${{ inputs.arch }}-cpm-
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ inputs.qtVersion }}
          arch: ${{ inputs.qtArch }}
          cache: true
          cache-key-prefix: ${{ inputs.os }}-${{ inputs.arch }}-${{ inputs.qtVersion }}-qt
      
      - name: Configure
        run: |
          cmake -S . -B build -GNinja -DCPM_SOURCE_CACHE=~/cpm-cache -DCMAKE_BUILD_TYPE=${{ inputs.buildType }} -DENABLE_UNITY=ON -DBUILD_TESTING=ON -DENABLE_DEPLOYMENT=ON
      
      - name: Build
        run: |
          cmake --build build --target all
      
      - name: Test
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          cd build
          ctest --output-on-failure

      - name: Deploy
        run: cmake --build build --target deploy

      - name: Get artifact name
        shell: bash
        run: |
          NAME="trackerboy-build-${{ inputs.platform }}-${{ inputs.arch }}"
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "artifactName=$NAME" >> $GITHUB_ENV
      
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifactName }}
          path: build/src/deploy/
