
name: '[develop] Build and deploy'
on:
  push:
    branches:
      - develop
    tags-ignore: '**'
    paths:
      - 'src/**'
      - 'test/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    name: '${{ matrix.os }}, ${{ matrix.arch }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: x64
            platform: osx
          - os: ubuntu-latest
            arch: x64
            platform: linux
          - os: windows-latest
            arch: x64
            platform: windows
            qtArch: win64_msvc2019_64
    uses: ./.github/workflows/buildAndDeploy.yml
    with:
      buildType: Debug
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      platform: ${{ matrix.platform }}
      qtArch: ${{ matrix.qtArch }}
      qtVersion: 6.4.0
  
