name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DENABLE_UI=OFF -DENABLE_TESTS=ON ..
    - name: build
      run: cmake --build build --config Debug
    - name: test
      run: |
        cd build
        ctest
