name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DTRACKERBOY_ENABLE_UI=OFF -DTRACKERBOY_ENABLE_TESTS=ON -DNO_VCPKG=ON ..
    - name: build
      run: cmake --build build --config Debug
    - name: test
      run: |
        cd build
        ctest
